<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQu3p7oh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQu3p7oh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQu3p7oh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQu3p7oh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQu3p7oh\appProdProjectContainer(array(
    'container.build_hash' => 'Qu3p7oh',
    'container.build_id' => 'a2813b81',
    'container.build_time' => 1538066684,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQu3p7oh');
