<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxffxbo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxffxbo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFxffxbo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFxffxbo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFxffxbo\appProdProjectContainer(array(
    'container.build_hash' => 'Fxffxbo',
    'container.build_id' => '7576837a',
    'container.build_time' => 1537968406,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxffxbo');
